import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const avenirNext = localFont({
  src: [
    {
      path: "./fonts/avenirRegular.otf",
      weight: "400",
      style: "normal",
    },

    {
      path: "./fonts/avenirBold.otf",
      weight: "700",
      style: "normal",
    },

    {
      path: "./fonts/avenirLite.otf",
      weight: "300",
      style: "normal",
    },
  ],
  variable: "--avenir",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${avenirNext.className}`}>{children}</body>
    </html>
  );
}
